added styling
ICTman1076/bins pull request #2
Opened 2019-10-11 19:44 UTC by rijusougata13

2019-10-11 19:54 UTC, ICTman1076 requested changes
Thanks for your PR! I'm a little confused by line 25, but other than that this is nice. Could you provide some explanation where asked please? Thanks :)

2019-10-11 19:54 UTC, ICTman1076 commented on snowy-silence-43C/index.html
> +      <h2>--LONks--</h2>
Not sure what the `--` does - could you explain a little further?

2019-10-11 19:54 UTC, ICTman1076 commented on snowy-silence-43C/index.html
> +  <style>.notEpic{background-color:coral;} .virus{color:red;} .notVirus{color:green;}</style>
Coral's a much better color, and using word-based colors makes sense. Nice work 👍

2019-10-11 19:58 UTC, rijusougata13 commented
"--lonks--" is  looking nice than "lonks".it doesn't matter actually.
but the colour "coral" matter in this case.

On Sat, 12 Oct, 2019, 1:24 AM ICTman1076, <notifications@github.com> wrote:

> *@ICTman1076* requested changes on this pull request.
>
> Thanks for your PR! I'm a little confused by line 25, but other than that
> this is nice. Could you provide some explanation where asked please? Thanks
> :)
> ------------------------------
>
> In snowy-silence-43C/index.html
> <https://github.com/ICTman1076/bins/pull/2#discussion_r334150839>:
>
> > @@ -22,14 +22,14 @@ <h1>{{ header.toLocaleUpperCase() }}</h1>
>
>        </ul>
>
>        <p>{{itemCount}} things.</p>
>
>        <p v-if="items.length === 0"><i>Nothing is epic :(</i></p>
>
> -      <h2>LONks</h2>
>
> +      <h2>--LONks--</h2>
>
>
> Not sure what the -- does - could you explain a little further?
> ------------------------------
>
> In snowy-silence-43C/index.html
> <https://github.com/ICTman1076/bins/pull/2#discussion_r334151193>:
>
> > @@ -5,10 +5,10 @@
>
>    <meta name="viewport" content="width=device-width">
>
>    <title>Very epic vue.js</title>
>
>    <script src="https://unpkg.com/vue"></script>
>
> -  <style>.notEpic{background-color:#FF0000;} .virus{color:#FF00FF;} .notVirus{color:#00FF00;}</style>
>
> +  <style>.notEpic{background-color:coral;} .virus{color:red;} .notVirus{color:green;}</style>
>
>
> Coral's a much better color, and using word-based colors makes sense. Nice
> work 👍
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ICTman1076/bins/pull/2?email_source=notifications&email_token=AMNRZE7CSUSKYH6UIKIEVLTQODKWPA5CNFSM4I76UNV2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCHXUZEQ#pullrequestreview-300895378>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMNRZE4F4Q5UXOBXWNBX5JTQODKWPANCNFSM4I76UNVQ>
> .
>

2019-10-11 20:01 UTC, ICTman1076 approved these changes
Ok, I've removed the double dash, but I'll keep everything else. I'm happy to merge this now. Thanks again :)

2019-10-11 20:02 UTC, merged

2019-10-12 04:38 UTC, rijusougata13 commented
ok

On Sat, 12 Oct, 2019, 1:32 AM ICTman1076, <notifications@github.com> wrote:

> Merged #2 <https://github.com/ICTman1076/bins/pull/2> into master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ICTman1076/bins/pull/2?email_source=notifications&email_token=AMNRZE2C4TQ36AXKSUIUIC3QODLUNA5CNFSM4I76UNV2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUFO5TLA#event-2707282348>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMNRZEYYY7MYW76R7WQYQQDQODLUNANCNFSM4I76UNVQ>
> .
>